version: "2"
services:
  vrlabs_node:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ../:/home/node/app
    expose:
      - "80"
    command: "npm start"

  # influxdb:
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - ./volumes/influxdb:/var/lib/influxdb
  #   image: "influxdb:latest"

  vrlabs_db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin#mariadb@1
    ports:
      - "3306:3306"
 #   volumes:
 #     - ./volumes/mariadb:/var/lib/mysql